name: manta_dart
version: 0.0.3
description: Manta Protocol implementation for Dart
author: Appia Systems Limited
homepage: http://appia.co
documentation: https://appiapay.github.io/manta-python
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  mqtt_client: ^5.6.0
  decimal: ^0.3.2
  uuid: ^2.0.2
  json_annotation: '>=2.0.0'
  logging: ^0.11.3+2
  pointycastle: ^1.0.0-rc4
  asn1lib: ^0.6.4
  rsa_pkcs: ^1.1.1
  async: ^2.2.0

dev_dependencies:
  test: ^1.3.4
  build_runner: ^1.0.0
  json_serializable: '>=2.0.0'
  mockito: ^3.0.0
  pedantic: ^1.8.0
